services:
    db:
        image: postgres:10
        restart: unless-stopped
        env_file: .env.local
        ports:
            - 5432:5432
        volumes:
            - ./.db/data:/var/lib/postgresql/data
